### ISSUE TITLE
Mac running on M1 Chip is not able to install the package

### ISSUE THREAD

**Issue by shivamiitgoa** [near/workspaces-js#110]
More details about the error:

```
(base) shivamkumar@Shivams-MacBook-Pro example % npx near-workspaces-init
Need to install the following packages:
  near-workspaces-init
Ok to proceed? (y) y
npm ERR! code 1
npm ERR! path /Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox
npm ERR! command failed
npm ERR! command sh -c node ./install.js
npm ERR! /Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox/dist/getBinary.js:13
npm ERR!     throw new Error(`Unsupported platform: ${type} ${arch}`);
npm ERR!     ^
npm ERR! 
npm ERR! Error: Unsupported platform: Darwin arm64
npm ERR!     at getPlatform (/Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox/dist/getBinary.js:13:11)
npm ERR!     at AWSUrl (/Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox/dist/getBinary.js:16:30)
npm ERR!     at getBinary (/Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox/dist/getBinary.js:27:19)
npm ERR!     at Object.<anonymous> (/Users/shivamkumar/projects/dragon/example/near-workspaces/node_modules/near-sandbox/dist/install.js:4:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1005:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:102:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shivamkumar/.npm/_logs/2022-02-11T14_06_56_244Z-debug.log
```

**Comment by ailisp** [comment]
As nearcore has dependencies that doesn't support M1 chip, we can only build nearcore and sandbox (a specially configured version of nearcore) as Darwin x86-64. So we'll need to fix: always download Darwin x86-64 build of sandbox binary. And M1 users will be able to run with rosetta

**Comment by shivamiitgoa** [comment]
Hey @ailisp 

I built the nearcore from the source but still when I am trying to install `near-workspaces-ava`, I am getting error.

**Comment by shivamiitgoa** [comment]
I am able to get it working using these steps: 

1. Remove node_modules and yarn.lock 
2. `arch -x86_64 zsh` This activates the cli in x64 mode
3. `yarn` to install dependencies

It worked after this 🎉

**Comment by shivamiitgoa** [comment]
I am closing this issue.

**Comment by tifrel** [comment]
@shivamiitgoa Your workaround seems to require a "dirty state" repo, as it didn't work after freshly running `npx near-workspaces-init`. A reproducible way to get it to install is:

```sh
yarn install # this will actually fail
arch -x86_64 zsh -c 'npm install'
```

Several other versions I tried didn't work, specifically I couldn't get it to work with either `yarn` or `npm` alone. `npm` complained about an old-format `package-lock.json` (which didn't exist when invoking it), but hey, it kind of works. I suggest to keep this open.
